baseURL = "https://juliaps.netlify.app"
languageCode = "en-us"
title = "Physiostirixis Κέντρο Φυσικοθεραπείας"
theme = "hugo-hero-theme"

[module]
  [module.hugoVersion]
    extended = true
    min = "0.92.0"
    
[params]
  google_analytics_id=""

  [params.logo]
    mobile = "images/logomob.png"
    mobile_height = "26px"
    mobile_width = "26px"
    desktop = "images/logo1.png"
    desktop_height = "36px"
    desktop_width = "25px"
    alt = "Physio Stirixis"

  [params.homepage_meta_tags]
    meta_description = "Hero is a multipurpose Hugo theme with fullscreen hero images and page sections. It contains content types for a business or portfolio site."
    meta_og_title = "Physio Stirixis Κέντρο Φυσικοθεραπείας"
    meta_og_type = "website"
    meta_og_url = "https://www.physiostirixis.gr"
    meta_og_image = "https://raw.githubusercontent.com/JugglerX/hugo-hero-theme/master/images/tn.png"
    meta_og_description = "This is the site of Physiostirixis with pedalographer and tecar therapy machine and plenty of other new technics."
    meta_twitter_card = "summary"
    meta_twitter_site = "@zerostaticio"
    meta_twitter_creator = "@zerostaticio"

[[menu.main]]
    name = "ΠΑΘΗΣΕΙΣ"
    url = "/ailments/"
    weight = 1

[[menu.main]]
	name = "ΕΞΟΠΛΙΣΜΟΣ"
	url = "/services/"
    weight = 2

[[menu.main]]
    name = "ΤΕΧΝΙΚΕΣ"
    url = "/technics/"
    weight = 3

[[menu.main]]
    name = "ΠΕΛΜΑΤΟΓΡΑΦΟΣ"
    url = "/pedalographer/"
    weight = 4


[[menu.main]]
    name = "ΘΕΡΑΠΕΙΑ TECAR"
    url = "/tecar/"
    weight = 5

[[menu.main]]
    name = "ΕΠΙΚΟΙΝΩΝΙΑ"
    url = "/contact/"
    weight = 6

[permalinks]
  post = "/:year/:month/:day/:slug/"
  pages = "/:filename/"
